### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by klinga** [BookOps-CAT/Bagel#8]
Find instructions in Github docs how to rename the `master` branch to `main`. Make the change. Don't forget to troubleshoot your local repo that still will have `master`.

**Comment by charlottekostelic** [comment]
Done.
(Note: in case this comes up in other repos, instructions on making this change are [here](https://gist.github.com/danieldogeanu/739f88ea5312aaa23180e162e3ae89ab))

**Comment by klinga** [comment]
👏 👏 👏
